version: 2.1.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
init:
- cmd: tzutil /s "Eastern Standard Time"
build_script:
- cmd: >-
    dotnet restore

    dotnet build -c Release
test_script:
- cmd: >-
    dotnet test tests/gitnstats.core.tests/gitnstats.core.tests.csproj
    
    dotnet test tests/gitnstats.test/gitnstats.test.csproj